language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  if: branch = master
  jobs:
    - CASSANDRA_ROLE="roles/cassandra_dba"
    - CASSANDRA_ROLE="roles/cassandra_firewall"
    - CASSANDRA_ROLE="roles/cassandra_install"
    - CASSANDRA_ROLE="roles/cassandra_linux"
    - CASSANDRA_ROLE="roles/cassandra_repository"
before_install:
  - python --version
  - pip install --upgrade pip
  - export pyv=$(python -c 'from platform import python_version; print(python_version()[:3])')
  - pip install --requirement requirements-${pyv}.txt
  - pip --version
  - ansible --version
  - molecule --version
  - pytest --version
script:
  - ./travis_run.sh
after_success:
  - codecov # submit coverage
