namespace: community
name: cassandra
version: 1.0.0
readme: README.md
authors: Rhys Campbell
description: null
license: null
license_file: null
tags: null
dependencies:
  community._general: '>=1.0'
  ansible.windows: '>=1.0'
repository: git@github.com:ansible-collections/cassandra.git
documentation: https://github.com/ansible-collections/cassandra/tree/master/docs
homepage: https://github.com/ansible-collections/cassandra
issues: https://github.com/ansible-collections/cassandra/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
