---
# tasks file for cassandra_nrpe
- name: Include vars for os family
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Ensure nrpe is installed
  package:
    name: "{{ nrpe_package }}"
    state: present

- name: Ensure Nagios server ip exists in allowed_hosts
  lineinfile:
    path: "{{ nrpe_cfg }}"
    regexp: "^allowed_hosts="
    line: "allowed_hosts={{ nrpe_allowed_hosts }}"
  notify:
     - Restart nrpe

- name: Install default nagios plugins
  package:
    name: "{{ nagios_plugins }}"
    state: present

- name: Install python-pip
  package:
    name: python-pip

- name: Ensure pip package requests is installed
  pip:
    name: requests

- name: Ensure py_check_jmx plugin exists
  copy:
    src: "{{ item }}"
    dest: "{{ nagios_plugin_dir }}"
    owner: nagios
    group: nagios
    mode: 0755
  with_items:
    - py_check_jmx
    - check_cassandra_cluster
