name: CI
on:
- pull_request

env:
  setup_cassandra_version_file: "./tests/integration/targets/setup_cassandra/defaults/main.yml"
  setup_ccm_version_file: "./tests/integration/targets/setup_cassandra_cluster_manager/defaults/main.yml"

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/community/cassandra

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install ansible-base (devel)
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color --python 3.6

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.6"]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/community/cassandra

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible-base (devel)
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Ensure cassandra versions are set to 311x
        run: |
          sed -i 's/^cassandra_version:.*/cassandra_version: \"311x\"/g' ${{ env.setup_cassandra_version_file }}
          sed -i 's/^cassandra_version:.*/cassandra_version: \"3.11.6\"/g' ${{ env.setup_ccm_version_file }}

      - name: Run integration tests on Python ${{ matrix.python_version }} & Cassandra 311x
        run: ansible-test integration --docker -v --color --retry-on-error --python ${{ matrix.python_version }} --continue-on-error --diff --coverage

      - name: Ensure cassandra versions are set to 22x
        run: |
          sed -i 's/^cassandra_version:.*/cassandra_version: \"22x\"/g' ${{ env.setup_cassandra_version_file }}
          sed -i 's/^cassandra_version:.*/cassandra_version: \"2.2.9\"/g' ${{ env.setup_ccm_version_file }}

      - name: Run integration tests on Python ${{ matrix.python_version }} & Cassandra 22x
        run: ansible-test integration --docker -v --color --retry-on-error --python ${{ matrix.python_version }} --continue-on-error --diff --coverage

      - name: Generate coverage report.
        run: ansible-test coverage xml -v --requirements --group-by command --group-by version

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false

      - name: Upload Coverage data
        run: tests/coverage.sh


# FIXME FUTURE: If Look if we want to split integration tests into it's own job if they are long running
# FIXME FUTURE: Other Python Versions
# FIXME FUTURE: Other Operating Systems
